---
- name: Load AddOnOperator metadata
  ansible.builtin.include_vars:
    file: "{{ role_path }}/meta/osac.yaml"
    name: addon_operator_metadata

- name: Ensure openshift-operators namespace exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: openshift-operators

- name: Create cert-manager Subscription
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ addon_operator_metadata.package_name }}"
        namespace: openshift-operators
      spec:
        channel: "{{ addon_operator_metadata.channel }}"
        installPlanApproval: Automatic
        name: "{{ addon_operator_metadata.package_name }}"
        source: "{{ addon_operator_metadata.catalog_source }}"
        sourceNamespace: "{{ addon_operator_metadata.catalog_source_namespace }}"

- name: Wait for cert-manager Subscription to resolve a CSV
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ addon_operator_metadata.package_name }}"
    namespace: openshift-operators
  register: cert_manager_subscription
  retries: 60
  delay: 5
  until:
    - cert_manager_subscription.resources | length == 1
    - cert_manager_subscription.resources[0].status.installedCSV is defined

- name: Wait for cert-manager CSV to succeed
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: "{{ cert_manager_subscription.resources[0].status.installedCSV }}"
    namespace: openshift-operators
  register: cert_manager_csv
  retries: 60
  delay: 5
  until:
    - cert_manager_csv.resources | length == 1
    - cert_manager_csv.resources[0].status.phase == "Succeeded"
