argument_specs:
  main:
    options:
      osac_cluster_templates:
        type: list
        description: Cluster templates to publish to the cluster_templates endpoint
      osac_compute_instance_templates:
        type: list
        description: ComputeInstance templates
      osac_addon_operator_templates:
        type: list
        description: AddOnOperator templates
        default: []
      osac_fulfillment_service_uri:
        type: str
        required: true
      osac_fulfillment_service_token:
        type: str
        required: true
      publish_templates_cluster_api_endpoint:
        type: str
        description: API endpoint for cluster templates
        default: "{{ osac_fulfillment_service_uri }}/api/private/v1/cluster_templates"
      publish_templates_compute_instance_api_endpoint:
        type: str
        description: API endpoint for ComputeInstance templates
        default: "{{ osac_fulfillment_service_uri }}/api/private/v1/compute_instance_templates"
      publish_templates_addon_operator_api_endpoint:
        type: str
        description: API endpoint for AddOnOperator templates
        default: "{{ osac_fulfillment_service_uri }}/api/private/v1/add_on_operators"
      publish_templates_addon_operator_update_mask:
        type: str
        description: Managed fields used when updating AddOnOperator templates
        default: "metadata.name,title,description,min_ocp_version,max_ocp_version,exclusions,dependencies"
